install	:
	pip install -r requirements_dev.txt

cleandep:
	pipreqs --clean requirements_dev.txt

getdep: 
	pipreqs --savepath requirements_dev.txt --force .

setenv:
	cp base.env .env

clean:
	find . -name "__pycache__" -type d -exec rm -rf {} +
	find . -name "*.pyc" -type f -delete


test:
	echo "testing"

venv:
	python -m venv .venv
	source .venv/Scripts/activate
	which python
	python -m pip install --upgrade pip
	pip install -r requirements_dev.txt

activate:
	source .venv/Scripts/activate

deactivate:
	deactivate
