install	:
	pip install -r requirements_dev.txt

cleandep:
	pipreqs --clean requirements_dev.txt

getdep: 
	pipreqs --savepath requirements.txt --force .

setenv:
	cp base.env .env

clean:
	rm -f -R */__pycache__ 

test:
	echo "testing"