install	:
	pip install -r requirements_dev.txt

cleandep:
	pipreqs --clean requirements_dev.txt

getdep: 
	pipreqs --savepath requirements_dev.txt --force .

setenv:
	cp base.env .env

clean:
	rm -f -R */__pycache__/* 
	rm -f -R ./*.pyc

test:
	echo "testing"
