CREATE EXTENSION IF NOT EXISTS pg_cron;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA PUBLIC;

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA PUBLIC;

GRANT USAGE ON SCHEMA cron TO test; -- need to get in env
