# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import app.grpc.agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Prompt = channel.unary_unary(
                '/agent.Agent/Prompt',
                request_serializer=agent__pb2.PromptRequest.SerializeToString,
                response_deserializer=agent__pb2.PromptAnswer.FromString,
                _registered_method=True)
        self.PromptStream = channel.unary_stream(
                '/agent.Agent/PromptStream',
                request_serializer=agent__pb2.PromptRequest.SerializeToString,
                response_deserializer=agent__pb2.PromptAnswer.FromString,
                _registered_method=True)
        self.StreamPrompt = channel.stream_unary(
                '/agent.Agent/StreamPrompt',
                request_serializer=agent__pb2.PromptRequest.SerializeToString,
                response_deserializer=agent__pb2.PromptAnswer.FromString,
                _registered_method=True)
        self.S2SPrompt = channel.stream_stream(
                '/agent.Agent/S2SPrompt',
                request_serializer=agent__pb2.PromptRequest.SerializeToString,
                response_deserializer=agent__pb2.PromptAnswer.FromString,
                _registered_method=True)


class AgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Prompt(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromptStream(self, request, context):
        """ServerSide Stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPrompt(self, request_iterator, context):
        """ClientSide Stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def S2SPrompt(self, request_iterator, context):
        """Bi-Directional Stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Prompt': grpc.unary_unary_rpc_method_handler(
                    servicer.Prompt,
                    request_deserializer=agent__pb2.PromptRequest.FromString,
                    response_serializer=agent__pb2.PromptAnswer.SerializeToString,
            ),
            'PromptStream': grpc.unary_stream_rpc_method_handler(
                    servicer.PromptStream,
                    request_deserializer=agent__pb2.PromptRequest.FromString,
                    response_serializer=agent__pb2.PromptAnswer.SerializeToString,
            ),
            'StreamPrompt': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamPrompt,
                    request_deserializer=agent__pb2.PromptRequest.FromString,
                    response_serializer=agent__pb2.PromptAnswer.SerializeToString,
            ),
            'S2SPrompt': grpc.stream_stream_rpc_method_handler(
                    servicer.S2SPrompt,
                    request_deserializer=agent__pb2.PromptRequest.FromString,
                    response_serializer=agent__pb2.PromptAnswer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.Agent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.Agent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Agent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Prompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.Agent/Prompt',
            agent__pb2.PromptRequest.SerializeToString,
            agent__pb2.PromptAnswer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromptStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent.Agent/PromptStream',
            agent__pb2.PromptRequest.SerializeToString,
            agent__pb2.PromptAnswer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPrompt(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/agent.Agent/StreamPrompt',
            agent__pb2.PromptRequest.SerializeToString,
            agent__pb2.PromptAnswer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def S2SPrompt(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/agent.Agent/S2SPrompt',
            agent__pb2.PromptRequest.SerializeToString,
            agent__pb2.PromptAnswer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
