# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import app.grpc.agent_pb2 as agent__pb2


class AgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Prompt = channel.unary_unary(
                '/agent.Agent/Prompt',
                request_serializer=agent__pb2.PromptRequest.SerializeToString,
                response_deserializer=agent__pb2.PromptAnswer.FromString,
                )
        self.PromptStream = channel.unary_stream(
                '/agent.Agent/PromptStream',
                request_serializer=agent__pb2.PromptRequest.SerializeToString,
                response_deserializer=agent__pb2.PromptAnswer.FromString,
                )
        self.StreamPrompt = channel.stream_unary(
                '/agent.Agent/StreamPrompt',
                request_serializer=agent__pb2.PromptRequest.SerializeToString,
                response_deserializer=agent__pb2.PromptAnswer.FromString,
                )
        self.S2SPrompt = channel.stream_stream(
                '/agent.Agent/S2SPrompt',
                request_serializer=agent__pb2.PromptRequest.SerializeToString,
                response_deserializer=agent__pb2.PromptAnswer.FromString,
                )
        self.Completion = channel.unary_unary(
                '/agent.Agent/Completion',
                request_serializer=agent__pb2.PromptRequest.SerializeToString,
                response_deserializer=agent__pb2.PromptAnswer.FromString,
                )
        self.S2SBatch = channel.stream_stream(
                '/agent.Agent/S2SBatch',
                request_serializer=agent__pb2.PromptRequest.SerializeToString,
                response_deserializer=agent__pb2.PromptAnswer.FromString,
                )


class AgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Prompt(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromptStream(self, request, context):
        """ServerSide Stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPrompt(self, request_iterator, context):
        """ClientSide Stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def S2SPrompt(self, request_iterator, context):
        """Bi-Directional Stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Completion(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def S2SBatch(self, request_iterator, context):
        """Bi-Directional Stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Prompt': grpc.unary_unary_rpc_method_handler(
                    servicer.Prompt,
                    request_deserializer=agent__pb2.PromptRequest.FromString,
                    response_serializer=agent__pb2.PromptAnswer.SerializeToString,
            ),
            'PromptStream': grpc.unary_stream_rpc_method_handler(
                    servicer.PromptStream,
                    request_deserializer=agent__pb2.PromptRequest.FromString,
                    response_serializer=agent__pb2.PromptAnswer.SerializeToString,
            ),
            'StreamPrompt': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamPrompt,
                    request_deserializer=agent__pb2.PromptRequest.FromString,
                    response_serializer=agent__pb2.PromptAnswer.SerializeToString,
            ),
            'S2SPrompt': grpc.stream_stream_rpc_method_handler(
                    servicer.S2SPrompt,
                    request_deserializer=agent__pb2.PromptRequest.FromString,
                    response_serializer=agent__pb2.PromptAnswer.SerializeToString,
            ),
            'Completion': grpc.unary_unary_rpc_method_handler(
                    servicer.Completion,
                    request_deserializer=agent__pb2.PromptRequest.FromString,
                    response_serializer=agent__pb2.PromptAnswer.SerializeToString,
            ),
            'S2SBatch': grpc.stream_stream_rpc_method_handler(
                    servicer.S2SBatch,
                    request_deserializer=agent__pb2.PromptRequest.FromString,
                    response_serializer=agent__pb2.PromptAnswer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.Agent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Agent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Prompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agent.Agent/Prompt',
            agent__pb2.PromptRequest.SerializeToString,
            agent__pb2.PromptAnswer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PromptStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/agent.Agent/PromptStream',
            agent__pb2.PromptRequest.SerializeToString,
            agent__pb2.PromptAnswer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamPrompt(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/agent.Agent/StreamPrompt',
            agent__pb2.PromptRequest.SerializeToString,
            agent__pb2.PromptAnswer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def S2SPrompt(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/agent.Agent/S2SPrompt',
            agent__pb2.PromptRequest.SerializeToString,
            agent__pb2.PromptAnswer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Completion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agent.Agent/Completion',
            agent__pb2.PromptRequest.SerializeToString,
            agent__pb2.PromptAnswer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def S2SBatch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/agent.Agent/S2SBatch',
            agent__pb2.PromptRequest.SerializeToString,
            agent__pb2.PromptAnswer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
