FROM redis:alpine AS redis-builder

FROM alpine:3.20 AS builder
RUN apk add --no-cache jq pwgen

FROM alpine/curl:latest

RUN apk add --no-cache jq coreutils
COPY --from=builder /usr/bin/jq /usr/bin/jq
COPY --from=builder /usr/bin/pwgen /usr/bin/pwgen
COPY --from=redis-builder /usr/local/bin/redis-cli /usr/local/bin/redis-cli

COPY ./scripts/ncs-utils.sh /ncs-utils.sh

ENTRYPOINT [""]