FROM notifyr/fastapi:community

ARG INSTALL_DOCLING=false

COPY --chown=notifyr:notifyr ./scripts/docling.sh .

RUN pip install langchain qdrant-client neo4j

RUN pip install llama-index-core llama-index-embeddings-openai llama-index-readers-file

RUN pip install arq  yake gensim 

RUN pip install langchain-anthropic  langchain-cohere langchain-groq langchain-openai

RUN ./docling.sh ${INSTALL_DOCLING}

COPY ./agentic_main.py ./agentic_main.py

COPY ./app/data_tasks.py ./data_tasks.py

