FROM redis:latest AS redis-builder

FROM alpine:3.20 AS builder
RUN apk add --no-cache curl jq

FROM alpine:3.20
COPY --from=builder /usr/bin/curl /usr/bin/curl
COPY --from=builder /usr/bin/jq /usr/bin/jq
COPY --from=redis-builder /usr/local/bin/redis-cli /usr/local/bin/redis-cli

COPY ./scripts/credits-utils.sh /credits-utils.sh

ENTRYPOINT ["/credits-utils.sh"]