FROM node:18-alpine

# install json-server
RUN npm install -g json-server

# RUN npm install yargs

RUN adduser -S setting

USER setting

WORKDIR /data

COPY ./settingdb/server.js ./

COPY ./settings_db.json /data/db.json

ENTRYPOINT [ ]
CMD ["json-server","--watch", "/data/db.json", "--host", "0.0.0.0", "--port" ,"3000"]