FROM golang:1.24.0 AS builder

WORKDIR /app

COPY ./balancer/ .
RUN go build -o balancer .

# Use a small base image for the final container
FROM debian:bookworm-slim
WORKDIR /root/
COPY --from=builder /app/balancer .
CMD ["./balancer"]
