# Build stage
FROM golang:1.24.0 AS builder
WORKDIR /app
COPY ./balancer/ .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o balancer .

# Final stage
FROM gcr.io/distroless/base-debian12:nonroot

COPY --from=builder /app/balancer /
USER nonroot:nonroot
ENTRYPOINT ["/balancer"]

