FROM python:3.10

WORKDIR /the/workdir/path

RUN apt-get update && apt-get install -y make

COPY ../app .

COPY requirements_dev.txt .

COPY MakeFile Makefile

RUN make install

RUN make celery_worker

