DROP SCHEMA IF EXISTS contacts CASCADE;
DROP SCHEMA IF EXISTS security CASCADE;
 

CREATE SCHEMA security;
CREATE SCHEMA contacts;


CREATE EXTENSION pg_cron;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA contacts;

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA security;

-- GRANT USAGE ON SCHEMA cron TO marco;